print("Hello World")
print('SRIRAM...198')
print("REDDY MITTANA")
print("REDDY MIT")
print("REDDY MITTA")
print("REDDY MITTA1")
print("REDDY MITTA2")
print("REDDY MITTA3")
print("REDDY MITTA4")
print("REDDY MITTA5")